(()=>{
'use strict';
const APP_VERSION='2026-08-08-2200';
const VERSION_URL='/version.json';
if(!sessionStorage.getItem('lulu_version_checked_'+APP_VERSION)){
  fetch(VERSION_URL+'?t='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(v=>{
    if(v&&v.version&&v.version!==APP_VERSION){
      sessionStorage.setItem('lulu_version_checked_'+v.version,'1');
      const u=new URL(location.href);u.searchParams.set('v',v.version);location.replace(u.href);
    }else sessionStorage.setItem('lulu_version_checked_'+APP_VERSION,'1');
  }).catch(()=>{});
}
const API='https://compresseur-luluclc3-vip.lucascl0606.workers.dev';
const sid=sessionStorage.getItem('lulu_session')||crypto.randomUUID();sessionStorage.setItem('lulu_session',sid);
const sessionStart=Number(sessionStorage.getItem('lulu_session_start')||Date.now());sessionStorage.setItem('lulu_session_start',String(sessionStart));
const base={session:sid,lang:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,screen:`${screen.width}x${screen.height}`};
window.trackEvent=async(type,data={})=>{try{await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'event',event:{...base,type,...data}})});}catch{}};
window.trackEvent('page_view');
window.addEventListener('pagehide',()=>{try{navigator.sendBeacon?.(API,new Blob([JSON.stringify({kind:'event',event:{...base,type:'session_end',durationMs:Date.now()-sessionStart}})],{type:'application/json'}),{keepalive:true}));}catch{}});
const style=document.createElement('style');style.textContent=`
.admin-modal{position:fixed;inset:0;background:rgba(3,4,9,.78);backdrop-filter:blur(22px) saturate(140%);z-index:100;display:grid;place-items:center;padding:12px;animation:adminIn .35s cubic-bezier(.2,.8,.2,1)}
.admin-modal.admin-hidden{display:none!important}.admin-box{width:min(1120px,100%);max-height:94vh;overflow:auto;background:linear-gradient(145deg,#111522f7,#090c13f7);border:1px solid #ffffff16;border-radius:28px;box-shadow:0 45px 140px #000,0 0 70px #8e75ff12;color:#f7f8fb;padding:24px;position:relative;isolation:isolate}.admin-box:before{content:"";position:absolute;inset:-1px;border-radius:28px;background:linear-gradient(120deg,#9c7dff22,transparent 35%,#65e6ff18);pointer-events:none;z-index:-1}.admin-box h2{font:800 clamp(25px,4vw,38px)/1 Manrope;margin:5px 0 7px;letter-spacing:-.04em}.admin-muted{color:#8f98a8;font-size:11px;line-height:1.6}.admin-close{position:absolute;right:15px;top:12px;width:38px;height:38px;border-radius:12px;background:#ffffff08;border:1px solid #ffffff0d;color:#aab2c0;font-size:24px;cursor:pointer;transition:.2s}.admin-close:hover{transform:rotate(90deg);background:#ffffff12}.admin-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.admin-kpi{background:linear-gradient(145deg,#ffffff07,#ffffff02);border:1px solid #ffffff0d;border-radius:17px;padding:15px;transition:.25s;animation:kpiIn .45s both}.admin-kpi:hover{transform:translateY(-3px);border-color:#9c7dff40;box-shadow:0 12px 35px #0005}.admin-kpi small{display:block;color:#737c8d;font-size:8px;letter-spacing:.12em}.admin-kpi b{display:block;font:800 21px Manrope;margin-top:6px}.admin-section{margin-top:22px}.admin-scroll{overflow:auto;border:1px solid #ffffff0d;border-radius:17px;background:#06080d99}.admin-table{width:100%;min-width:980px;border-collapse:collapse;font-size:10px}.admin-table th,.admin-table td{text-align:left;padding:10px;border-bottom:1px solid #ffffff09}.admin-table th{color:#7f8999;font-size:8px;letter-spacing:.1em;position:sticky;top:0;background:#0b0e15}.admin-table tbody tr{transition:.15s}.admin-table tbody tr:hover{background:#ffffff04}.admin-pill{display:inline-block;padding:4px 7px;border-radius:99px;background:#151a25;color:#b8c0cf}.admin-note{margin-top:12px;padding:12px;border:1px solid #ffffff0d;border-radius:13px;color:#8791a1;font-size:9px;line-height:1.6;background:#ffffff03}.admin-hidden{display:none!important}.admin-live{display:inline-flex;align-items:center;gap:7px;margin-top:10px;color:#72e6ac;font-size:9px;font-weight:800;letter-spacing:.08em}.admin-live i{width:7px;height:7px;border-radius:50%;background:#72e6ac;box-shadow:0 0 0 0 #72e6ac66;animation:pulse 1.6s infinite}.admin-error{color:#ff8294;font-size:10px;margin-top:8px;text-align:center}@keyframes adminIn{from{opacity:0;transform:scale(.97) translateY(12px)}to{opacity:1;transform:none}}@keyframes kpiIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes pulse{70%{box-shadow:0 0 0 9px transparent}100%{box-shadow:0 0 0 0 transparent}}@media(max-width:720px){.admin-grid{grid-template-columns:1fr 1fr}.admin-box{padding:18px;border-radius:22px}.admin-box:before{border-radius:22px}}
`;document.head.appendChild(style);
let adminModal=null,token='';
function createDashboard(){if(adminModal)return adminModal;adminModal=document.createElement('div');adminModal.className='admin-modal admin-hidden';adminModal.innerHTML=`<div class="admin-box"><button class="admin-close" aria-label="Fermer">×</button><div class="eyebrow">ESPACE CRÉATEUR</div><h2>Centre de contrôle</h2><p class="admin-muted">Vue complète de l’activité technique du compresseur, pensée pour téléphone et ordinateur.</p><div class="admin-live"><i></i> ANALYTICS EN DIRECT · MÉMOIRE TEMPORAIRE</div><div class="admin-grid"><div class="admin-kpi"><small>VISITES</small><b id="akVisits">0</b></div><div class="admin-kpi"><small>SESSIONS</small><b id="akSessions">0</b></div><div class="admin-kpi"><small>OPÉRATIONS</small><b id="akOps">0</b></div><div class="admin-kpi"><small>SUCCÈS</small><b id="akSuccess">0%</b></div><div class="admin-kpi"><small>FICHIERS</small><b id="akFiles">0</b></div><div class="admin-kpi"><small>ENTRÉE</small><b id="akIn">0 B</b></div><div class="admin-kpi"><small>SORTIE</small><b id="akOut">0 B</b></div><div class="admin-kpi"><small>ÉCONOMIE</small><b id="akSave">0%</b></div></div><div class="admin-section"><div class="eyebrow">ACTIVITÉ RÉCENTE</div><div class="admin-scroll"><table class="admin-table"><thead><tr><th>HEURE</th><th>TYPE</th><th>SESSION</th><th>OPÉRATION</th><th>FICHIERS</th><th>AVANT</th><th>APRÈS</th><th>PROFIL</th><th>SUCCÈS</th><th>PAYS</th><th>VILLE</th><th>RÉSEAU</th><th>ÉCRAN</th></tr></thead><tbody id="adminRows"></tbody></table></div></div><div class="admin-note">Aucun contenu de fichier n’est conservé. Les IP brutes et mots de passe ne sont pas enregistrés. Les métadonnées réseau affichées viennent de Cloudflare. Les analytics en mémoire peuvent disparaître lors du recyclage du Worker.</div></div>`;document.body.appendChild(adminModal);adminModal.querySelector('.admin-close').onclick=()=>adminModal.classList.add('admin-hidden');adminModal.addEventListener('click',e=>{if(e.target===adminModal)adminModal.classList.add('admin-hidden')});return adminModal}
const fmt=n=>{n=Number(n)||0;if(!n)return'0 B';const u=['B','Ko','Mo','Go','To'],i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+' '+u[i]};
async function openAdmin(code,errorEl){if(errorEl)errorEl.textContent='';try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'admin',code})});const j=await r.json();if(!j.ok)throw new Error('Code Admin incorrect ou non configuré sur le Worker.');token=j.token;const d=createDashboard();d.classList.remove('admin-hidden');await load()}catch(e){if(errorEl)errorEl.textContent=e.message||'Impossible de joindre le serveur Admin.'}}
async function load(){try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'list',token})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erreur de récupération');render(j.events||[])}catch(e){const rows=document.querySelector('#adminRows');if(rows)rows.innerHTML=`<tr><td colspan="13">${e.message}</td></tr>`}}
function render(ev){const q=s=>document.querySelector(s),sessions=new Set(ev.map(x=>x.session).filter(Boolean)),visits=ev.filter(x=>x.type==='page_view').length,ops=ev.filter(x=>x.type==='operation_complete'||x.type==='operation_error'),success=ops.filter(x=>x.success).length,files=ops.reduce((a,x)=>a+(x.files||0),0),bin=ops.reduce((a,x)=>a+(x.bytesIn||0),0),bout=ops.reduce((a,x)=>a+(x.bytesOut||0),0),save=bin?Math.max(0,(1-bout/bin)*100):0;q('#akVisits').textContent=visits;q('#akSessions').textContent=sessions.size;q('#akOps').textContent=ops.length;q('#akSuccess').textContent=(ops.length?success/ops.length*100:0).toFixed(0)+'%';q('#akFiles').textContent=files;q('#akIn').textContent=fmt(bin);q('#akOut').textContent=fmt(bout);q('#akSave').textContent=save.toFixed(1)+'%';q('#adminRows').innerHTML=ev.slice(0,250).map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td><span class="admin-pill">${x.type}</span></td><td>${String(x.session||'').slice(0,8)}</td><td>${x.operation||'—'}</td><td>${x.files||0}</td><td>${fmt(x.bytesIn)}</td><td>${fmt(x.bytesOut)}</td><td>${x.profile||'—'}</td><td>${x.success?'✓':'✕'}</td><td>${x.country||'—'}</td><td>${x.city||'—'}</td><td>${x.asOrganization||'—'}</td><td>${x.screen||'—'}</td></tr>`).join('')||'<tr><td colspan="13">Aucune activité enregistrée.</td></tr>'}
const fileCount=()=>document.querySelectorAll('#files .file').length;document.querySelector('#start')?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'compression',files:fileCount(),profile:document.querySelector('.choice.active')?.dataset.profile||'smart'}),true);document.querySelector('#extract')?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'decompression',files:fileCount(),profile:'zip'}),true);
let lastResult=false;const result=document.querySelector('#result');if(result){const observer=new MutationObserver(()=>{const visible=!result.classList.contains('hidden');if(visible&&!lastResult){const toBytes=t=>{const m=String(t||'').match(/([\d.,]+)\s*(B|Ko|Mo|Go|To)/i);if(!m)return 0;return Number(m[1].replace(',','.'))*({B:1,Ko:1024,Mo:1024**2,Go:1024**3,To:1024**4}[m[2]])};window.trackEvent?.('operation_complete',{operation:($('#resultEyebrow')?.textContent||'').includes('DÉCOMPRESSION')?'decompression':'compression',files:fileCount()||1,bytesIn:toBytes($('#before')?.textContent),bytesOut:toBytes($('#after')?.textContent),savedPct:Number(String($('#saving')?.textContent||'').replace(',','.'))||0,profile:document.querySelector('.choice.active')?.dataset.profile||'smart',success:true})}lastResult=visible});observer.observe(result,{attributes:true,attributeFilter:['class']})}
function hookVip(){const btn=document.querySelector('#unlock'),input=document.querySelector('#code'),err=document.querySelector('#error');if(!btn||!input||btn.dataset.adminHook)return;btn.dataset.adminHook='1';const submit=async e=>{if(input.value.trim()!=='luluadmin')return;e.preventDefault();e.stopImmediatePropagation();await openAdmin(input.value.trim(),err)};btn.addEventListener('click',submit,true);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim()==='luluadmin')submit(e)},true)}
hookVip();new MutationObserver(hookVip).observe(document.documentElement,{childList:true,subtree:true});
})();
