(()=>{
const API='https://compresseur-luluclc3-vip.lucascl0606.workers.dev';
const $=s=>document.querySelector(s);
const sid=sessionStorage.getItem('lulu_session')||crypto.randomUUID();sessionStorage.setItem('lulu_session',sid);
const sessionStart=Number(sessionStorage.getItem('lulu_session_start')||Date.now());sessionStorage.setItem('lulu_session_start',String(sessionStart));
const base={session:sid,lang:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,screen:`${screen.width}x${screen.height}`};
window.trackEvent=async(type,data={})=>{try{await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'event',event:{...base,type,...data}})});}catch{}};
window.trackEvent('page_view');
window.addEventListener('pagehide',()=>{try{navigator.sendBeacon?.(API,new Blob([JSON.stringify({kind:'event',event:{...base,type:'session_end',durationMs:Date.now()-sessionStart}})],{type:'application/json'}));}catch{}});
const style=document.createElement('style');style.textContent=`
.admin-open{border:1px solid #315b63!important;background:#0c2024!important;color:#9ef0ff!important;margin-left:6px}.admin-modal{position:fixed;inset:0;background:#000c;backdrop-filter:blur(14px);z-index:100;display:grid;place-items:center;padding:16px}.admin-box{width:min(1050px,100%);max-height:92vh;overflow:auto;background:#0e1118;border:1px solid #31515d;border-radius:24px;box-shadow:0 40px 120px #000;padding:26px;color:#f7f8fb}.admin-box h2{font:800 30px Manrope;margin:5px 0 8px}.admin-muted{color:#8f98a8;font-size:11px;line-height:1.6}.admin-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.admin-kpi{background:#090c11;border:1px solid #272d39;border-radius:14px;padding:15px}.admin-kpi small{display:block;color:#737c8d;font-size:8px;letter-spacing:.12em}.admin-kpi b{display:block;font:800 21px Manrope;margin-top:6px}.admin-table{width:100%;border-collapse:collapse;font-size:10px}.admin-table th,.admin-table td{text-align:left;padding:9px;border-bottom:1px solid #242936}.admin-table th{color:#7f8999;font-size:8px;letter-spacing:.1em}.admin-pill{display:inline-block;padding:4px 7px;border-radius:99px;background:#151a25;color:#b8c0cf}.admin-close{float:right;background:none;border:0;color:#8992a2;font-size:28px;cursor:pointer}.admin-input{width:100%;padding:13px;background:#080a0e;border:1px solid #2a303d;color:white;border-radius:11px;outline:none}.admin-btn{border:0;border-radius:11px;padding:13px 17px;font-weight:800;cursor:pointer;background:linear-gradient(100deg,#9879ff,#65e4ff);color:#08090d}.admin-danger{color:#ff9aa9}.admin-section{margin-top:22px}.admin-scroll{overflow:auto}.admin-note{margin-top:12px;padding:11px;border:1px solid #2a303d;border-radius:11px;color:#8791a1;font-size:9px}.admin-hidden{display:none!important}@media(max-width:720px){.admin-grid{grid-template-columns:1fr 1fr}.admin-box{padding:18px}.admin-table{min-width:780px}}
`;document.head.appendChild(style);
const btn=document.createElement('button');btn.className='vip admin-open';btn.textContent='⚙ Admin';btn.title='Accès créateur';$('#vipOpen')?.after(btn);
const modal=document.createElement('div');modal.className='admin-modal admin-hidden';modal.innerHTML=`<div class="admin-box"><button class="admin-close">×</button><div class="eyebrow">ACCÈS CRÉATEUR</div><h2>Tableau de bord Admin</h2><p class="admin-muted">Accès réservé au créateur. Les données affichées sont des statistiques d’usage, pas le contenu des fichiers.</p><div id="adminAuth"><label class="admin-muted">Code admin</label><input class="admin-input" id="adminCode" type="password" autocomplete="off" placeholder="Code secret"><button class="admin-btn" id="adminUnlock" style="margin-top:10px">Ouvrir l’Admin</button><div id="adminError" class="admin-danger" style="font-size:10px;margin-top:8px"></div></div><div id="adminDash" class="admin-hidden"><div class="admin-grid"><div class="admin-kpi"><small>VISITES</small><b id="kVisits">0</b></div><div class="admin-kpi"><small>SESSIONS</small><b id="kSessions">0</b></div><div class="admin-kpi"><small>OPÉRATIONS</small><b id="kOps">0</b></div><div class="admin-kpi"><small>TAUX DE SUCCÈS</small><b id="kSuccess">0%</b></div><div class="admin-kpi"><small>FICHIERS</small><b id="kFiles">0</b></div><div class="admin-kpi"><small>OCTETS ENTRÉE</small><b id="kIn">0 B</b></div><div class="admin-kpi"><small>OCTETS SORTIE</small><b id="kOut">0 B</b></div><div class="admin-kpi"><small>ÉCONOMIE</small><b id="kSave">0%</b></div></div><div class="admin-section"><div class="eyebrow">ACTIVITÉ RÉCENTE</div><div class="admin-scroll"><table class="admin-table"><thead><tr><th>HEURE</th><th>TYPE</th><th>SESSION</th><th>OPÉRATION</th><th>FICHIERS</th><th>AVANT</th><th>APRÈS</th><th>PROFIL</th><th>SUCCÈS</th><th>PAYS</th><th>APPAREIL</th></tr></thead><tbody id="adminRows"></tbody></table></div></div><div class="admin-note">Les fichiers, leur contenu, les mots de passe et les IP brutes ne sont pas enregistrés. Le pays est approximatif via Cloudflare. Les événements sont conservés 30 jours dans le stockage Analytics du Worker.</div></div></div>`;document.body.appendChild(modal);
let token='';const close=()=>modal.classList.add('admin-hidden');modal.querySelector('.admin-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});btn.onclick=()=>{modal.classList.remove('admin-hidden');$('#adminCode').focus()};
const fmt=n=>{n=Number(n)||0;if(!n)return'0 B';const u=['B','Ko','Mo','Go','To'],i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+' '+u[i]};
async function unlock(){const code=$('#adminCode').value;$('#adminError').textContent='';try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'admin',code})});const j=await r.json();if(!j.ok)throw new Error('Code incorrect');token=j.token;$('#adminAuth').classList.add('admin-hidden');$('#adminDash').classList.remove('admin-hidden');await load()}catch(e){$('#adminError').textContent=e.message||'Impossible de joindre le serveur Admin.'}}
async function load(){try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'list',token})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erreur');render(j.events||[])}catch(e){$('#adminRows').innerHTML=`<tr><td colspan="11" class="admin-danger">${e.message}</td></tr>`}}
function render(ev){const sessions=new Set(ev.map(x=>x.session).filter(Boolean)),visits=ev.filter(x=>x.type==='page_view').length,ops=ev.filter(x=>x.type==='operation_complete'||x.type==='operation_error'),success=ops.filter(x=>x.success).length,files=ops.reduce((a,x)=>a+(x.files||0),0),bin=ops.reduce((a,x)=>a+(x.bytesIn||0),0),bout=ops.reduce((a,x)=>a+(x.bytesOut||0),0),save=bin?Math.max(0,(1-bout/bin)*100):0;$('#kVisits').textContent=visits;$('#kSessions').textContent=sessions.size;$('#kOps').textContent=ops.length;$('#kSuccess').textContent=(ops.length?(success/ops.length*100):0).toFixed(0)+'%';$('#kFiles').textContent=files;$('#kIn').textContent=fmt(bin);$('#kOut').textContent=fmt(bout);$('#kSave').textContent=save.toFixed(1)+'%';$('#adminRows').innerHTML=ev.slice(0,250).map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td><span class="admin-pill">${x.type}</span></td><td>${String(x.session||'').slice(0,8)}</td><td>${x.operation||'—'}</td><td>${x.files||0}</td><td>${fmt(x.bytesIn)}</td><td>${fmt(x.bytesOut)}</td><td>${x.profile||'—'}</td><td>${x.success?'✓':'✕'}</td><td>${x.country||'—'}</td><td title="${String(x.userAgent||'').replace(/"/g,'&quot;')}">${x.screen||'—'}</td></tr>`).join('')||'<tr><td colspan="11">Aucune activité enregistrée.</td></tr>'}
const start=$('#start'),extract=$('#extract');start?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'compression',files:Array.isArray(window.files)?window.files.length:0,profile:window.profile||'smart'}),true);extract?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'decompression',files:Array.isArray(window.files)?window.files.length:0,profile:'zip'}),true);
let lastResult=false;const result=$('#result');if(result)new MutationObserver(()=>{const visible=!result.classList.contains('hidden');if(visible&&!lastResult){const beforeText=$('#before')?.textContent||'0',afterText=$('#after')?.textContent||'0',toBytes=t=>{const m=String(t).match(/([\d.,]+)\s*(B|Ko|Mo|Go|To)/i);if(!m)return 0;return Number(m[1].replace(',','.'))*({B:1,Ko:1024,Mo:1024**2,Go:1024**3,To:1024**4}[m[2]]);};window.trackEvent?.('operation_complete',{operation:($('#resultEyebrow')?.textContent||'').includes('DÉCOMPRESSION')?'decompression':'compression',files:Array.isArray(window.files)?window.files.length:1,bytesIn:toBytes(beforeText),bytesOut:toBytes(afterText),savedPct:Number(String($('#saving')?.textContent||'').replace(',','.'))||0,profile:window.profile||'smart',success:true});}lastResult=visible})({});
$('#adminUnlock').onclick=unlock;$('#adminCode').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});
})();
