(()=>{
const API='https://compresseur-luluclc3-vip.lucascl0606.workers.dev';
const sid=sessionStorage.getItem('lulu_session')||crypto.randomUUID();sessionStorage.setItem('lulu_session',sid);
const sessionStart=Number(sessionStorage.getItem('lulu_session_start')||Date.now());sessionStorage.setItem('lulu_session_start',String(sessionStart));
const base={session:sid,lang:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,screen:`${screen.width}x${screen.height}`};
window.trackEvent=async(type,data={})=>{try{await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'event',event:{...base,type,...data}})});}catch{}};
window.trackEvent('page_view');
window.addEventListener('pagehide',()=>{try{navigator.sendBeacon?.(API,new Blob([JSON.stringify({kind:'event',event:{...base,type:'session_end',durationMs:Date.now()-sessionStart}})],{type:'application/json'}));}catch{}});
const style=document.createElement('style');style.textContent=`
.admin-inline{display:flex;gap:8px;align-items:center;margin-top:12px;padding-top:12px;border-top:1px solid #272b38}.admin-inline input{flex:1}.admin-inline button{white-space:nowrap}.admin-error{color:#ff8294;font-size:10px;min-height:14px;margin-top:7px;text-align:center}.admin-modal{position:fixed;inset:0;background:#000c;backdrop-filter:blur(14px);z-index:100;display:grid;place-items:center;padding:16px}.admin-box{width:min(1050px,100%);max-height:92vh;overflow:auto;background:#0e1118;border:1px solid #31515d;border-radius:24px;box-shadow:0 40px 120px #000;color:#f7f8fb;padding:26px}.admin-box h2{font:800 30px Manrope;margin:5px 0 8px}.admin-muted{color:#8f98a8;font-size:11px;line-height:1.6}.admin-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.admin-kpi{background:#090c11;border:1px solid #272d39;border-radius:14px;padding:15px}.admin-kpi small{display:block;color:#737c8d;font-size:8px;letter-spacing:.12em}.admin-kpi b{display:block;font:800 21px Manrope;margin-top:6px}.admin-table{width:100%;border-collapse:collapse;font-size:10px}.admin-table th,.admin-table td{text-align:left;padding:9px;border-bottom:1px solid #242936}.admin-table th{color:#7f8999;font-size:8px;letter-spacing:.1em}.admin-pill{display:inline-block;padding:4px 7px;border-radius:99px;background:#151a25;color:#b8c0cf}.admin-close{float:right;background:none;border:0;color:#8992a2;font-size:28px;cursor:pointer}.admin-btn{border:0;border-radius:11px;padding:13px 17px;font-weight:800;cursor:pointer;background:linear-gradient(100deg,#9879ff,#65e4ff);color:#08090d}.admin-section{margin-top:22px}.admin-scroll{overflow:auto}.admin-note{margin-top:12px;padding:11px;border:1px solid #2a303d;border-radius:11px;color:#8791a1;font-size:9px}.admin-hidden{display:none!important}@media(max-width:720px){.admin-inline{flex-direction:column;align-items:stretch}.admin-grid{grid-template-columns:1fr 1fr}.admin-box{padding:18px}.admin-table{min-width:900px}}
`;document.head.appendChild(style);
let adminModal=null,token='';
function createDashboard(){if(adminModal)return adminModal;adminModal=document.createElement('div');adminModal.className='admin-modal admin-hidden';adminModal.innerHTML=`<div class="admin-box"><button class="admin-close">×</button><div class="eyebrow">ACCÈS CRÉATEUR</div><h2>Tableau de bord Admin</h2><p class="admin-muted">Statistiques techniques et activité du site. Aucun contenu de fichier n’est conservé.</p><div class="admin-grid"><div class="admin-kpi"><small>VISITES</small><b id="akVisits">0</b></div><div class="admin-kpi"><small>SESSIONS</small><b id="akSessions">0</b></div><div class="admin-kpi"><small>OPÉRATIONS</small><b id="akOps">0</b></div><div class="admin-kpi"><small>SUCCÈS</small><b id="akSuccess">0%</b></div><div class="admin-kpi"><small>FICHIERS</small><b id="akFiles">0</b></div><div class="admin-kpi"><small>ENTRÉE</small><b id="akIn">0 B</b></div><div class="admin-kpi"><small>SORTIE</small><b id="akOut">0 B</b></div><div class="admin-kpi"><small>ÉCONOMIE</small><b id="akSave">0%</b></div></div><div class="admin-section"><div class="eyebrow">ACTIVITÉ RÉCENTE</div><div class="admin-scroll"><table class="admin-table"><thead><tr><th>HEURE</th><th>TYPE</th><th>SESSION</th><th>OPÉRATION</th><th>FICHIERS</th><th>AVANT</th><th>APRÈS</th><th>PROFIL</th><th>SUCCÈS</th><th>PAYS</th><th>VILLE</th><th>RÉSEAU</th><th>ÉCRAN</th></tr></thead><tbody id="adminRows"></tbody></table></div></div><div class="admin-note">Les IP brutes, le contenu et les mots de passe ne sont pas enregistrés. Les informations réseau affichées sont les métadonnées Cloudflare disponibles pour la requête. La mémoire Analytics est temporaire et peut disparaître lors du recyclage du Worker.</div></div>`;document.body.appendChild(adminModal);adminModal.querySelector('.admin-close').onclick=()=>adminModal.classList.add('admin-hidden');adminModal.addEventListener('click',e=>{if(e.target===adminModal)adminModal.classList.add('admin-hidden')});return adminModal}
const fmt=n=>{n=Number(n)||0;if(!n)return'0 B';const u=['B','Ko','Mo','Go','To'],i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+' '+u[i]};
async function openAdmin(code,errorEl){errorEl.textContent='';try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'admin',code})});const j=await r.json();if(!j.ok)throw new Error('Code admin incorrect');token=j.token;const d=createDashboard();d.classList.remove('admin-hidden');await load()}catch(e){errorEl.textContent=e.message||'Impossible de joindre le serveur Admin.'}}
async function load(){try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'list',token})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erreur');render(j.events||[])}catch(e){const rows=document.querySelector('#adminRows');if(rows)rows.innerHTML=`<tr><td colspan="13" class="admin-danger">${e.message}</td></tr>`}}
function render(ev){const q=s=>document.querySelector(s),sessions=new Set(ev.map(x=>x.session).filter(Boolean)),visits=ev.filter(x=>x.type==='page_view').length,ops=ev.filter(x=>x.type==='operation_complete'||x.type==='operation_error'),success=ops.filter(x=>x.success).length,files=ops.reduce((a,x)=>a+(x.files||0),0),bin=ops.reduce((a,x)=>a+(x.bytesIn||0),0),bout=ops.reduce((a,x)=>a+(x.bytesOut||0),0),save=bin?Math.max(0,(1-bout/bin)*100):0;q('#akVisits').textContent=visits;q('#akSessions').textContent=sessions.size;q('#akOps').textContent=ops.length;q('#akSuccess').textContent=(ops.length?success/ops.length*100:0).toFixed(0)+'%';q('#akFiles').textContent=files;q('#akIn').textContent=fmt(bin);q('#akOut').textContent=fmt(bout);q('#akSave').textContent=save.toFixed(1)+'%';q('#adminRows').innerHTML=ev.slice(0,250).map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td><span class="admin-pill">${x.type}</span></td><td>${String(x.session||'').slice(0,8)}</td><td>${x.operation||'—'}</td><td>${x.files||0}</td><td>${fmt(x.bytesIn)}</td><td>${fmt(x.bytesOut)}</td><td>${x.profile||'—'}</td><td>${x.success?'✓':'✕'}</td><td>${x.country||'—'}</td><td>${x.city||'—'}</td><td>${x.asOrganization||'—'}</td><td>${x.screen||'—'}</td></tr>`).join('')||'<tr><td colspan="13">Aucune activité enregistrée.</td></tr>'}
function installVipAdmin(){const vip=document.querySelector('#vipOpen');if(!vip)return false;if(vip.dataset.adminInstalled==='1')return true;vip.dataset.adminInstalled='1';vip.addEventListener('click',()=>{setTimeout(()=>{const box=document.querySelector('.modal:not(.hidden) .modalbox')||document.querySelector('.modalbox');if(!box||box.querySelector('.admin-inline'))return;const row=document.createElement('div');row.className='admin-inline';row.innerHTML=`<input id="adminCodeInline" type="password" autocomplete="off" placeholder="Code admin"><button class="admin-btn" id="adminInlineBtn" type="button">⚙ Admin</button>`;const err=document.createElement('div');err.className='admin-error';err.id='adminInlineError';box.appendChild(row);box.appendChild(err);const input=row.querySelector('#adminCodeInline'),btn=row.querySelector('#adminInlineBtn');const go=()=>openAdmin(input.value,err);btn.onclick=go;input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});},80)},true);return true}
installVipAdmin();new MutationObserver(installVipAdmin).observe(document.documentElement,{childList:true,subtree:true});
const fileCount=()=>document.querySelectorAll('#files .file').length;const start=document.querySelector('#start'),extract=document.querySelector('#extract');start?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'compression',files:fileCount(),profile:document.querySelector('.choice.active')?.dataset.profile||'smart'}),true);extract?.addEventListener('click',()=>window.trackEvent?.('operation_start',{operation:'decompression',files:fileCount(),profile:'zip'}),true);
let lastResult=false;const result=document.querySelector('#result');if(result){const observer=new MutationObserver(()=>{const visible=!result.classList.contains('hidden');if(visible&&!lastResult){const toBytes=t=>{const m=String(t||'').match(/([\d.,]+)\s*(B|Ko|Mo|Go|To)/i);if(!m)return 0;return Number(m[1].replace(',','.'))*({B:1,Ko:1024,Mo:1024**2,Go:1024**3,To:1024**4}[m[2]]);};window.trackEvent?.('operation_complete',{operation:($('#resultEyebrow')?.textContent||'').includes('DÉCOMPRESSION')?'decompression':'compression',files:fileCount()||1,bytesIn:toBytes($('#before')?.textContent),bytesOut:toBytes($('#after')?.textContent),savedPct:Number(String($('#saving')?.textContent||'').replace(',','.'))||0,profile:document.querySelector('.choice.active')?.dataset.profile||'smart',success:true});}lastResult=visible});observer.observe(result,{attributes:true,attributeFilter:['class']});}
})();
