(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const style=document.createElement('style');style.textContent=`.ux-recompress{display:none;margin-top:14px;padding:14px;border:1px solid #272c38;border-radius:12px;background:#090b10;color:#aeb5c3;font-size:10px;line-height:1.6}.ux-recompress.on{display:block}.ux-recompress b{color:#fff}.ux-mode{color:#c9bfff}.ux-working{margin-top:14px;padding:13px;border:1px solid #272c38;border-radius:12px;background:#090b10}.ux-working .head{display:flex;justify-content:space-between;font:700 12px Manrope}.ux-working .bar{height:8px;background:#05070a;border-radius:99px;overflow:hidden;margin:9px 0}.ux-working i{display:block;width:0;height:100%;background:linear-gradient(90deg,#9d7eff,#64e6ff)}.ux-working small{color:#78808f;font-size:9px}`;document.head.appendChild(style);
const tabs=$$('.tab'),card=$('.card'),selection=$('#selection');if(!card)return;let uxMode='compress';
const rt=document.createElement('button');rt.className='tab';rt.textContent='Recompresser';rt.dataset.ux='recompress';$('.tabs')?.appendChild(rt);
const info=document.createElement('div');info.className='ux-recompress';info.id='uxInfo';info.innerHTML='♻️ <b>Recompression intelligente</b><br>Extrait une archive ZIP puis la reconstruit. Le VIP utilise le niveau maximal. Le contenu original n’est jamais modifié.';selection?.appendChild(info);
const work=document.createElement('div');work.className='ux-working hidden';work.id='uxWork';work.innerHTML='<div class="head"><span id="uxTitle">Recompression</span><span id="uxPct">0%</span></div><div class="bar"><i id="uxBar"></i></div><small id="uxMsg">Préparation locale…</small>';selection?.appendChild(work);
function setUXMode(m){uxMode=m;info.classList.toggle('on',m==='recompress');tabs.forEach(t=>t.classList.toggle('active',m==='recompress'?false:t.dataset.ux!=='recompress'&&((m==='compress'&&t.textContent.trim()==='Compresser')||(m==='decompress'&&t.textContent.trim()==='Décompresser'))));if(m==='recompress'){$('#compressControls')?.classList.add('hidden');$('#decompControls')?.classList.add('hidden');$('#start').textContent='Recompresser l’archive →'}else if(m==='compress'){$('#compressControls')?.classList.remove('hidden');$('#decompControls')?.classList.add('hidden')}else{$('#compressControls')?.classList.add('hidden');$('#decompControls')?.classList.remove('hidden')}}
tabs.forEach(t=>t.addEventListener('click',()=>setTimeout(()=>setUXMode(t.textContent.trim()==='Décompresser'?'decompress':'compress'),0)));rt.addEventListener('click',()=>{setUXMode('recompress');rt.classList.add('active');tabs.forEach(t=>t.classList.remove('active'));});
function show(p,msg){work.classList.remove('hidden');$('#uxPct').textContent=Math.round(p)+'%';$('#uxBar').style.width=p+'%';$('#uxMsg').textContent=msg}function hide(){setTimeout(()=>work.classList.add('hidden'),800)}
const start=$('#start');if(start)start.addEventListener('click',async e=>{if(uxMode!=='recompress')return; e.preventDefault();e.stopImmediatePropagation();const inp=$('#picker');const fs=inp?.files||[];if(fs.length!==1||!fs[0].name.toLowerCase().endsWith('.zip')){alert('Choisis une seule archive .zip pour la recompression.');return}try{const f=fs[0];show(8,'Lecture de l’archive…');const buf=new Uint8Array(await f.arrayBuffer());show(25,'Analyse des fichiers…');await new Promise(r=>setTimeout(r,20));const entries=fflate.unzipSync(buf),names=Object.keys(entries),data={};for(let i=0;i<names.length;i++){data[names[i]]=entries[names[i]];show(25+i/names.length*55,`Extraction ${i+1} / ${names.length} : ${names[i]}`);await new Promise(r=>setTimeout(r,0))}const vip=$('#vipOpen')?.textContent.includes('actif'),level=vip?9:5;show(88,'Reconstruction ZIP…');await new Promise(r=>setTimeout(r,20));const zipped=fflate.zipSync(data,{level}),blob=new Blob([zipped],{type:'application/zip'});show(100,'Recompression terminée.');hide();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='recompresse-luluclc3.zip';a.textContent='Télécharger l’archive recompressée ↓';a.className='btn primary';a.style.display='inline-block';a.style.marginTop='14px';info.appendChild(document.createElement('br'));info.appendChild(a);if(zipped.length<f.size)info.insertAdjacentHTML('beforeend',`<br><span class="ux-mode">Gain : ${(100-(zipped.length/f.size)*100).toFixed(1)} %.</span>`);else info.insertAdjacentHTML('beforeend','<br><span>La nouvelle archive n’est pas plus petite : le contenu reste intact.</span>')}catch(err){console.error(err);hide();alert('Cette archive ne peut pas être recompressée avec ce moteur.')}} ,true);
})();