const cors={'Access-Control-Allow-Origin':'https://luluclc3.github.io','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'content-type','Cache-Control':'no-store'};
const events=globalThis.__LULU_ANALYTICS__||(globalThis.__LULU_ANALYTICS__=[]),MAX_EVENTS=500;
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}});
const enc=s=>new TextEncoder().encode(s);
const b64url=b=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const unb64url=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
async function sign(v,secret){const k=await crypto.subtle.importKey('raw',enc(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc(v))))}
async function issueToken(role,env){const payload={role,iat:Date.now(),exp:Date.now()+1800000,jti:crypto.randomUUID()};const p=b64url(enc(JSON.stringify(payload)));return p+'.'+await sign(p,env.ADMIN_SECRET||env.ADMIN_CODE||'')}
async function validToken(token,role,env){try{const [p,s]=String(token||'').split('.');if(!p||!s)return false;const expected=await sign(p,env.ADMIN_SECRET||env.ADMIN_CODE||'');if(s!==expected)return false;const d=JSON.parse(new TextDecoder().decode(unb64url(p)));return d.role===role&&d.exp>Date.now()}catch{return false}}
async function match(v,e){const a=enc(typeof v==='string'?v:''),b=enc(e||'');if(!b.length||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
const num=(v,min=0,max=1e15)=>{const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):0},text=(v,m=120)=>String(v??'').slice(0,m);
function recordEvent(event,request){const cf=request.cf||{};const safe={id:crypto.randomUUID(),ts:Date.now(),type:text(event.type||'unknown',40),session:text(event.session,80),durationMs:num(event.durationMs,0,604800000),operation:text(event.operation,40),files:num(event.files,0,999),bytesIn:num(event.bytesIn),bytesOut:num(event.bytesOut),savedPct:Number.isFinite(Number(event.savedPct))?Math.max(-100,Math.min(100,Number(event.savedPct))):null,profile:text(event.profile,30),success:event.success!==false,lang:text(event.lang,30),timezone:text(event.timezone,80),screen:text(event.screen,30),userAgent:text(request.headers.get('User-Agent'),240),acceptLanguage:text(request.headers.get('Accept-Language'),160),referer:text(request.headers.get('Referer'),240),country:text(request.headers.get('CF-IPCountry')||cf.country,4),continent:text(cf.continent,8),region:text(cf.region,80),city:text(cf.city,80),postalCode:text(cf.postalCode,24),cfTimezone:text(cf.timezone,80),latitude:text(cf.latitude,32),longitude:text(cf.longitude,32),colo:text(cf.colo,16),asn:num(cf.asn,0,2**32),asOrganization:text(cf.asOrganization,160),httpProtocol:text(cf.httpProtocol,20),tlsVersion:text(cf.tlsVersion,30),tlsCipher:text(cf.tlsCipher,60)};events.unshift(safe);if(events.length>MAX_EVENTS)events.length=MAX_EVENTS}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(request.method!=='POST')return response({ok:false,error:'Method not allowed'},405);if(request.headers.get('Origin')!=='https://luluclc3.github.io')return response({ok:false,error:'Forbidden'},403);let body;try{body=await request.json()}catch{return response({ok:false,error:'Invalid JSON'},400)}
if(body?.kind==='auth'){if(await match(body.code,env.ADMIN_CODE||env.ADMIN_SECRET||''))return response({ok:true,role:'admin',token:await issueToken('admin',env)});if(await match(body.code,env.VIP_CODE||''))return response({ok:true,role:'vip',token:await issueToken('vip',env)});return response({ok:false,error:'Invalid code'},401)}
if(body?.kind==='admin'){if(!(await match(body.code,env.ADMIN_CODE||env.ADMIN_SECRET||'')))return response({ok:false,error:'Invalid code'},401);return response({ok:true,token:await issueToken('admin',env)})}
if(body?.kind==='event'){recordEvent(body.event||{},request);return response({ok:true,buffered:events.length})}
if(body?.kind==='list'){if(!(await validToken(body.token,'admin',env)))return response({ok:false,error:'Unauthorized'});return response({ok:true,events:events.slice(0,500),meta:{now:Date.now(),buffered:events.length,maxBuffered:MAX_EVENTS,persistent:false,storage:'worker-memory'}})}
return response({ok:false,error:'Unknown request'},400)}};
